[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "https://rvkocbmfpwjsnnumawqd.supabase.co/rest/v1/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  REACT_APP_SUPABASE_URL = "https://rvkocbmfpwjsnnumawqd.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2a29jYm1mcHdqc25udW1hd3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNzc3NzcsImV4cCI6MjA1MDk1Mzc3N30.ZftdgexAE6b2NzQF9HuQ1_mD6TMXJJGfGI7lNWWz8pU"
  REACT_APP_ENV = "production"
